### ISSUE TITLE
Feature Request - update snippet chunks

### ISSUE THREAD

**Issue by ChrstnMgcn** [sergant210/tagElementPlugin#4]
This has become one of my favorite and most useful extras. Thank you so much!

The only thing that would help even more would be to be able to edit the chunk templates called from within snippet properties.

[[getImageList? &docid=`3` &tpl=`gilTestimonial`]]

I can work around it by temporarily adding a $ in the chunk name (&tpl=`$gilTestimonial`), but on a few occasions I was nested about 6 chunks in and forgot. When I saved the parent chunks I ended up getting no display or an output of the array (getResources) because no tpl chunk was defined.

Seriously though, it's a pretty minor inconvenience, but it would be fantastic if that could be added somehow.

Thanks again!

**Comment by sergant210** [comment]
I think the solution is one more hotkey for chunks.

**Comment by sergant210** [comment]
Now you can forget about adding the $. Select chunk name and press Ctrl+Alt+C. I hope you enjoy it.

**Comment by ChrstnMgcn** [comment]
Sorry it's taken me so long to write back... with this change I've been getting so much more done! Seriously! Thank you sooo much!
