### ISSUE TITLE
TypeError since in MODX 2.5.7/8 and 2.6.0

### ISSUE THREAD

**Issue by jonleverrier** [sergant210/tagElementPlugin#5]
tagElementPlugin is generating a TypeError since MODX 2.5.7. It is also generating the same error in MODX 2.6.

# Steps to reproduce

1. Install a clean installation of MODX 2.6.0
2. Install tagElementPlugin via the package manager
3. Edit a resource

# Observed behaviour 
Check your browser for the console error:
```
tagelementplugin.js:57 Uncaught TypeError: Cannot read property 'addKeyListener' of null
    at Object.initialize (tagelementplugin.js:57)
    at tagelementplugin.js:458
    at ext-all.js:21
    at b (ext-all.js:21)
```
This might be related to:
https://github.com/modxcms/revolution/issues/13682

**Comment by sergant210** [comment]
TagElementPlugin does not support rich text editors. Read the documentation.
