### ISSUE TITLE
Fantastic... but maybe a new feature?

### ISSUE THREAD

**Issue by kolbykruger** [sergant210/tagElementPlugin#6]
First, this extra is absolutely the best thing ever!

Second,
I would love for this to work a little differently on things like pdoresources, where you never really intend to edit the actual plugin php files, but rather the &tpl specified in the call. I wonder if there is some way to get it so it looks for the &tpl as a chunk rather than the pdoresources php file itself.

Just a thought, but thank you for this regardless!

**Comment by sergant210** [comment]
Can you explain more in detail? I do not quite understand what you are talking about.

**Comment by kolbykruger** [comment]
Hi @sergant210,

Here is an example:

Lets say I have a pdoResources call on the home page of a site to pull in 3 blog posts. I would have this pdoResource call on the template, and then inside that call an `&tpl=` that refers to a chunk to "loop" the resources through.

``[[pdoResources? &parents=`5` &limit=`3`  &tpl=`blogs.tpl`]]``

Right now when clicking control+enter on this call, it opens the pdoResources snippet, which you would never actually edit. Instead, it would be cool for your extra to look for the `&tpl=` specified in the pdoResources call, and open that chunk instead.

Right now to get it to open that chunk in the pdoResources call, I would have to wrap it in [[$ and ]], and that isn't feasible. 

Does that make sense? Just a suggestion! But thanks for your awesome extra!

**Comment by sergant210** [comment]
First, you don't need to select "[[" and "]]" to open the element dialog.
Second, you are not very attentive. Select "blogs.tpl" and press Ctrl+Alt+C.  I think you will be happy )

**Comment by kolbykruger** [comment]
Hilariously, I had something else macro'd to Ctrl+Alt+C so when I tried that before, it did not work. Damn AHK. This is absolutely fantastic! You're awesome!
